# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-16 00:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_code', models.CharField(max_length=8)),
                ('country_code', models.CharField(max_length=3)),
                ('agency_site_key', models.CharField(db_index=True, max_length=12)),
                ('local_id', models.CharField(db_index=True, max_length=3, verbose_name='Local Identifier')),
                ('facility_type', models.CharField(max_length=12)),
                ('effective_date', models.DateTimeField(verbose_name='Record Effective Date')),
                ('city', models.CharField(max_length=64)),
                ('facility_name', models.CharField(max_length=64, null=True)),
                ('elevation', models.IntegerField(null=True)),
                ('elevation_units', models.CharField(max_length=2, null=True)),
                ('tpa_agl', models.IntegerField(null=True, verbose_name='Traffic Pattern Altitude (TPA), distance above ground (AGL)')),
                ('tpa_agl_units', models.CharField(max_length=2, null=True, verbose_name='TPA (AGL) Units')),
                ('magnetic_variation_degrees', models.IntegerField(null=True)),
                ('magnetic_variation_direction', models.CharField(max_length=2, null=True)),
                ('magnetic_variation_year', models.IntegerField(null=True)),
                ('ctaf_frequency', models.DecimalField(decimal_places=3, max_digits=6, null=True, verbose_name='Common Traffic Advisory Frequency (CTAF)')),
                ('icao_id', models.CharField(db_index=True, max_length=4, null=True, verbose_name='ICAO Identifier')),
                ('is_public_use', models.NullBooleanField()),
                ('activation_date', models.DateField(null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='Runway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agency_site_key', models.CharField(db_index=True, max_length=12)),
                ('runway_id', models.CharField(max_length=8)),
                ('runway_length', models.IntegerField(null=True)),
                ('runway_length_units', models.CharField(max_length=2, null=True)),
                ('runway_width', models.IntegerField(null=True)),
                ('runway_width_units', models.CharField(max_length=2, null=True)),
                ('base_end_id', models.CharField(max_length=4)),
                ('base_end_traffic_dir', models.CharField(max_length=1)),
                ('reciprocal_end_id', models.CharField(max_length=4)),
                ('reciprocal_end_traffic_dir', models.CharField(max_length=1)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='runways', to='airports.Facility')),
            ],
        ),
    ]
